name: Build Docker

on: [push]

jobs:
  build:
    env:
      NIM_VERSION: 1.0.2
      HELLOWORLD_VERSION: 0.1

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Build
      run: docker build -t helloworld:$HELLOWORLD_VERSION -f dockerfiles/ubuntu-1.0.2 .

    - name: Test
      run: docker run --rm helloworld:$HELLOWORLD_VERSION

    - name: List docker images
      run: docker images
