name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Install Nim
      run: export CHOOSENIM_CHOOSE_VERSION="1.0.2"

    - run: |
        curl https://nim-lang.org/choosenim/init.sh -sSf > init.sh
        sh init.sh -y

    - run: export PATH=$HOME/.nimble/bin:$PATH

    - run: nimble build -y
