name: Build

on: [push]

jobs:
  build:
    env:
      NIM_VERSION: 1.0.2

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Cache choosenim
      id: cache-choosenim
      uses: actions/cache@v1
      with:
        path: ~/.choosenim
        key: ${{ runner.os }}-choosenim-$NIM_VERSION

    - name: Cache nimble
      id: cache-nimble
      uses: actions/cache@v1
      with:
        path: ~/.nimble
        key: ${{ runner.os }}-nimble-$NIM_VERSION

    - name: Install Nim
      if: steps.cache-choosenim.outputs.cache-hit != 'true' || steps.cache-nimble.outputs.cache-hit != 'true'
      run: |
        export CHOOSENIM_CHOOSE_VERSION="$NIM_VERSION"
        curl https://nim-lang.org/choosenim/init.sh -sSf > init.sh
        sh init.sh -y

    - name: Build project
      run: |
        export PATH=$HOME/.nimble/bin:$PATH
        echo $PATH
        nimble build -y
        mkdir -p rel
        mv hello_world rel/

    - name: Run Tests
      run: |
        export PATH=$HOME/.nimble/bin:$PATH
        echo $PATH
        nimble test

    - name: Upload artifact
      uses: actions/upload-artifact@master
      with:
        name: release
        path: rel
