name: Build DockerHub Image

on: [push]

jobs:
  build:
    env:
      AUTHOR: hiteshjasani
      REPO: nim-hello-world
      IMAGE: hello-world-ubuntu
      VERSION: 0.1

    strategy:
      matrix:
        NIM_VERSION: [1.0.2, 1.0.6, 1.2.0]

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build
      run: docker build -t $AUTHOR/$REPO:$IMAGE-$VERSION-${{ matrix.NIM_VERSION }} -f dockerfiles/build-${{ matrix.NIM_VERSION }}-ubuntu .

    - name: Test
      run: docker run --rm $AUTHOR/$REPO:$IMAGE-$VERSION-${{ matrix.NIM_VERSION }}

    - name: List docker images
      run: docker images

    - name: Log in to DockerHub
      run: echo $TOKEN | docker login -u $AUTHOR --password-stdin
      env:
        TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Publish image to DockerHub
      run: docker push $AUTHOR/$REPO:$IMAGE-$VERSION-${{ matrix.NIM_VERSION }}

    - name: Log out of DockerHub
      if: always()
      run: docker logout
