name: Build GH Packages Image

#on: [push]

jobs:
  build:
    env:
      AUTHOR: hiteshjasani
      REPO: nim-hello-world
      IMAGE: hello-world-ubuntu
      VERSION: 0.1
      NIM_VERSION: 1.0.2
      IMAGE_SVR: docker.pkg.github.com

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build
      run: docker build -t $IMAGE_SVR/$AUTHOR/$REPO/$IMAGE:$VERSION -f dockerfiles/build-$NIM_VERSION-ubuntu .

    - name: Test
      run: docker run --rm $IMAGE_SVR/$AUTHOR/$REPO/$IMAGE:$VERSION

    - name: List docker images
      run: docker images

    - name: Log in to Github Packages
      run: echo $TOKEN | docker login $IMAGE_SVR -u $AUTHOR --password-stdin
      env:
        TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Publish image to Github Packages
      run: docker push $IMAGE_SVR/$AUTHOR/$REPO/$IMAGE:$VERSION

    - name: Log out of Github Packages
      if: always()
      run: docker logout $IMAGE_SVR
