name: Build Docker

on: [push]

jobs:
  build:
    env:
      NIM_VERSION: 1.0.2

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Build
      run: |
        docker run -v `pwd`:/usr/src/app -w /usr/src/app nimlang/nim:$NIM_VERSION nimble build -y
        mkdir -p rel
        mv hello_world rel/

    - name: Upload artifact
      uses: actions/upload-artifact@master
      with:
        name: release
        path: rel
