name: Test

on: [push]

jobs:
  build:
    env:
      AUTHOR: hiteshjasani
      REPO: nim-hello-world
      IMAGE: hello-world-ubuntu
      VERSION: 0.1
      NIM_VERSION: 1.0.2

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Test
      run: docker run -v `pwd`:/usr/src/app -w /usr/src/app nimlang/nim:$NIM_VERSION nimble test -y
